CREATE TABLE IF NOT EXISTS goal
(
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    GOAL TEXT NOT NULL,
    GOAL_NAME VARCHAR(128),
    GOAL_CATEGORY VARCHAR(255),
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES userData(id)
    );